name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build

    - name: Test global installation
      run: |
        npm pack
        npm install -g ./feral-code-*.tgz
        feral-code --version

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Create GitHub Release Assets
      run: |
        tar -czf feral-code-${{ github.event.release.tag_name }}.tar.gz dist/
        zip -r feral-code-${{ github.event.release.tag_name }}.zip dist/

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./feral-code-${{ github.event.release.tag_name }}.tar.gz
        asset_name: feral-code-${{ github.event.release.tag_name }}.tar.gz
        asset_content_type: application/gzip